name: cicd test
on: [push]

jobs:
  build_and_test:
    runs-on: macos-12
    strategy:
        matrix:
            name: ["MacOSX/Static/X64/Debug", "MacOSX/Static/X64/Release"]
            os: [macos-10.15]
            config: [Debug, Release]
            args: [""]
    steps:
      - uses: actions/checkout@v2
      - name: Set up CMake
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
